### ISSUE TITLE
Possible wireless hardware alternatives for APs

### ISSUE THREAD

**Issue by sarcasticadmin** [socallinuxexpo/scale-network#410]
## Description
Keeping track of the existing alternatives in the space to replace the WNDR 3700v2, 3800 series of APs

Current options:
- ~~`TPLink C2600`~~ - https://www.tp-link.com/us/home-networking/wifi-router/archer-c2600/ (Denied) - Moving away from due to instability of the radio drivers: https://github.com/socallinuxexpo/scale-network/issues/281
- `Belkin RT-3200` - https://openwrt.org/toh/linksys/e8450 (current front runner) - A few team members have this AP and the support from the openwrt community looks promising
- `MochaBin-5G` - https://www.cnx-software.com/2021/10/03/mochabin-5g-openwrt-ubuntu-sbc-10gbe-wifi-6-5g/
- `BPI-R2` - https://www.banana-pi.org/r2.html
- `TP-Link EAP615-Wall` - https://github.com/socallinuxexpo/scale-network/issues/594
- `Mikrotik hPA ax2` - https://github.com/socallinuxexpo/scale-network/issues/604

## Acceptance Criteria
  - Built in wireless chipset thats relevant with current client chipsets
  - Affordable price per unit ~ $50
  - Support well by recent versions of openwrt
  - Open hardware (nice to have)

**Comment by davidelang** [comment]
one that was recommended (haven't researched it) is https://www.amazon.com/gp/product/B08LMQLG7X

linksys ax3200 with stock firmware it says max 25 devices, don't know if that 
limit remains with openwrt

lists at $150

David Lang

**Comment by ptrlow1** [comment]
Another one that's supported is the TP-Link EAP615-Wall v1 

Here is the wiki page on OpenWrt's site: https://openwrt.org/toh/tp-link/eap615-wall
IEEE 802.11ax gigabit PoE+ (802.3af/at) wall-mount access point. Has a single PoE+ input ethernet jack on the back. Three additional ethernet jacks with one providing pass-through PoE output (802.3at) on the bottom.

Right now on Amazon it is priced at $89 (as of 7/27/2022; shipped direct from Amazon); has a MediaTek MT7621AT chip (880 MHz; 16MB flash; 128MB of ram); it's also has PoE.(don't know if the switches work with these...)

There's also the Ubiquiti UniFi 6LR, but advise not to use it. (The company has a hostile relationship against open firmware like OpenWrt.)

**Comment by ptrlow1** [comment]
Maybe too late for 20x, maybe for 21x. Also looking at the Netgear WAX202 which has gained official openwrt support, it is ax1800 and claims 128 max clients (stock firmware), is priced on amazon around $50. Uses simular hardware as the mentioned "EAP615-Wall" but with more memory and ram.

There is also a Netgear WAX206 which has similar hardware as the belkin rt3200/linksys rt8450, but with a 2.5G wan port; price on amazon is around ~$90. Note that isn't supported at this time, but a pr was submitted last month for official support (https://github.com/openwrt/openwrt/pull/11363). Note the 2.5G wan is supported but only with stock firmware, otherwise up to 1g when used with openwrt.

Openwrt pages:
WAX202: https://openwrt.org/toh/hwdata/netgear/netgear_wax202
WAX206: https://openwrt.org/inbox/toh/netgear/wax206

**Comment by ptrlow1** [comment]
Also looking at the Netgear WAX202 which has gained official openwrt support, it is ax1800 and claims 128 max clients (stock firmware), is priced on Amazon around ~$50. Uses simular hardware as the mentioned "EAP615-Wall" but with more memory and ram.

There is also a Netgear WAX206 which has similar hardware as the Belkin rt3200/Linksys rt8450 which has ax3200, but with a 2.5G wan port, also claims 128 max devices (stock fw); price on Amazon is around ~$90. Note that isn't supported at this time, but a pr was submitted last month for official support (https://github.com/openwrt/openwrt/pull/11363). Note the 2.5G wan is supported but only with stock firmware, otherwise up to 1g when used with openwrt.

Openwrt hardware pages:
WAX202: https://openwrt.org/toh/hwdata/netgear/netgear_wax202
WAX206: https://openwrt.org/inbox/toh/netgear/wax206

**Comment by ptrlow1** [comment]
Probability too late for 20x, but maybe for the following show ie 21x. Would be better than the tp-link poe ap.

**Comment by owendelong** [comment]
A 2.5G WAN port doesn’t do us any good. Our infrastructure hardware is capable of 1G and 10G. It won’t do 2.5G.

Owen

**Comment by sarcasticadmin** [comment]
> A 2.5G WAN port doesn’t do us any good. Our infrastructure hardware is capable of 1G and 10G. It won’t do 2.5G.

@owendelong while the 2.5G WAN port doesnt sway the decision, I think its still worth considering the hardware if its more widely available and the price is equal to/or better than the  Belkin rt3200/Linksys rt8450. Assuming the support from the openwrt project is there

@ptrlow1 thank you for the additional insight on these options, this definitely is worth considering!

**Comment by ptrlow1** [comment]
Linksys EA8450/Belkin RT3200 uses MediaTek MT7622BV (ARM Cortex A53; ARMv8 64-Bit).

**Comment by davidelang** [comment]
restating the requirements

MU-MIMO support
OpenWRT support
<$200 per unit

desirable
PoE support
no external antennas (they tangle in storage boxes and get broken)
lower price is better :-)

**Comment by nixinator** [comment]
I think it's not off topic to mention this imitative. I've not used it, or don't know if its ready to use in any form.
https://openwifi.tip.build/about/about-openwifi

**Comment by davidelang** [comment]
the fact that you have to sign up with them to get access to thier list of 
supported hardware is a strike against them in my opinion.

I'm considering it, trying to find from their public information what their big 
advantage is.

David Lang

**Comment by davidelang** [comment]
looking through this, they are building everything into a single config 
(registry style) and that is far more limiting than OpenWRT that exposes a full 
linux system. As a result I'm not going to register with them to get access.

David Lang

**Comment by sarcasticadmin** [comment]
Closing as weve opted to go with and currently support the Belkin RT3200 (Linksys E8450): https://github.com/socallinuxexpo/scale-network/issues/532
